name: Code Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, mysql

      - name: Install Composer dependencies
        working-directory: project-app
        run: composer install --prefer-dist --no-interaction

      - name: Wait for MySQL to be ready
        run: sleep 15

      - name: Run database migrations
        working-directory: project-app
        run: php artisan migrate --force

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Vite dependencies
        working-directory: project-app
        run: npm install

      - name: Run Laravel tests
        working-directory: project-app
        run: php artisan test
