name: CI/CD

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Set to your PHP version
        extensions: mbstring, xml, gd, curl, mysqlnd

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Run tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Only run this job if the build job is successful

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to the server
      run: |
        rsync -avz --delete ./ root@165.22.59.23:/var/www/html/laravel-app/project-app
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Apache
      run: ssh -o StrictHostKeyChecking=no root@<your-droplet-ip> 'systemctl restart apache2'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
