name: CI/CD

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: fixedasset
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, mysql

      - name: Install Composer dependencies
        working-directory: project-app
        run: composer install --prefer-dist --no-interaction

      - name: Create .env file
        run: |
          cat <<EOF > project-app/.env
          APP_NAME=Laravel
          APP_ENV=testing
          APP_KEY=$(php project-app/artisan key:generate --show)
          APP_DEBUG=true
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=fixedasset
          DB_USERNAME=root
          DB_PASSWORD=password
          EOF

      - name: Wait for MySQL to be ready
        run: sleep 15

      - name: Run database migrations and seeders
        working-directory: project-app
        run: php artisan migrate:fresh --seed --force

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or the version you are using

      - name: Install Vite dependencies
        working-directory: project-app
        run: npm install

      - name: Build Vite assets
        working-directory: project-app
        run: npm run build # Ensure this is the correct command for your build

      - name: Run Laravel tests
        working-directory: project-app
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh  # Create the .ssh directory
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to the server
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@165.22.59.23:/var/www/html/laravel-app/project-app
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Apache
      run: ssh -o StrictHostKeyChecking=no root@<your-droplet-ip> 'systemctl restart apache2'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
