name: Super-linter

on: push  # Triggers on every push to any branch

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Pulls the latest code

      - name: Install Composer dependencies
        run: |
          cd project-app
          composer install --no-interaction --prefer-dist --no-dev

      - name: Run Super-Linter
        uses: github/super-linter@v5  # Runs the linter on your code
        env:
          DEFAULT_BRANCH: main  # Checks code against the 'main' branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provides authentication

      - name: Clean workspace
        run: git clean -xfd